version: 0.0
os: linux
files:
  - source: /
    destination: /etc/ansible/codedeploy
hooks:
  BeforeInstall:
    - location: codedeploy-scripts/before_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: codedeploy-scripts/application_start.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: codedeploy-scripts/verify_service.sh
      timeout: 300
      runas: root